### ISSUE TITLE
Merging Installation and Hardware

### ISSUE THREAD

**Issue by modelmat** [Chameleon-Vision/chameleon-docs#3]
![image](https://user-images.githubusercontent.com/25718989/70130418-a5dfb200-16d4-11ea-9cc2-e11bf647c639.png)

These are both rather empty sections and I believe "Supported Hardware" could be merged into the "Installation" section.

Thoughts?

**Comment by Bankst** [comment]
As we get close to finishing up SolvePNP, we will be researching adding support for dozens of co-processors, and having a single place to refer to the hardware specifics of them will be good to have. Gonna close this for now as a `wont-fix`
