### ISSUE TITLE
Documentation doesn't make certain aspects of setup process clear

### ISSUE THREAD

**Issue by CJKeller03** [Chameleon-Vision/chameleon-docs#9]
It could be helpful to mention that there must be code running on the robot before the Chameleon server is started in order for the network tables to function properly. I ran into this problem (documented on [Chief Delphi](https://www.chiefdelphi.com/t/accessing-chameleon-vision-network-table-data-within-labview/373287/7)) while trying to use Chameleon with LabView, and was unable to find any mention of this in the Chameleon documentation. If it is there and I just missed it, maybe making it more conspicuous would prevent others from also running into this?

I think it would also be helpful to mention whether it is necessary to set up the netmask and gateway in the [building a 2d pipeline section](https://chameleon-vision.readthedocs.io/en/latest/getting-started/building-2d-pipeline.html) and if so, give examples as to what to use.

Thanks for your work on this project, and if you need a LabView code example for the documentation I can provide one!

**Comment by oriagranat9** [comment]
That has been already fixed and now the order of startup does not matter, would love to get a labview example of you can

**Comment by CJKeller03** [comment]
Sure! How should I send it to you?

**Comment by oriagranat9** [comment]
Send the example to chameleonvis@gmail.com

**Comment by CJKeller03** [comment]
Will do. Thanks!
